[build]
  command = "pnpm run build" 
  publish = "dist"
  functions = "netlify/functions" # ⬅️ ADD: Define the folder where Netlify should look for functions
  environment = { NODE_VERSION = "20" }

# CRITICAL FOR FIXING THE WHITE SCREEN ON DEEP LINKS (SPA ROUTING)
[[redirects]]
  # This rule handles all static client routes (e.g., /settings)
  from = "/*"
  to = "/index.html"
  status = 200

# ⬅️ ADD THIS REDIRECT BLOCK
[[redirects]]
  # 1. THIS TARGETS ALL API CALLS (e.g., /api/data)
  from = "/api/*"
  # 2. THIS FORWARDS THE REQUEST TO THE NETLIFY FUNCTION NAMED 'api'
  to = "/.netlify/functions/api/:splat" 
  status = 200
